### ISSUE TITLE
Colab notebook does not work

### ISSUE THREAD

**Issue by ma7555** [peteryuX/arcface-tf2#43]
```
Traceback (most recent call last):
  File "test.py", line 77, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "test.py", line 31, in main
    training=False)
  File "/content/arcface-tf2/modules/models.py", line 82, in ArcFaceModel
    x = Backbone(backbone_type=backbone_type, use_pretrain=use_pretrain)(x)
  File "/content/arcface-tf2/modules/models.py", line 32, in backbone
    weights=weights)(x_in)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/applications/__init__.py", line 46, in wrapper
    return base_fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/applications/resnet.py", line 33, in ResNet50
    return resnet.ResNet50(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keras_applications/resnet_common.py", line 435, in ResNet50
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keras_applications/resnet_common.py", line 411, in ResNet
    model.load_weights(weights_path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/training.py", line 234, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1222, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 651, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by kjaleph** [comment]
@ma7555 Run below:   
`pip install 'h5py<3.0.0`'
The error is happening due to newer version of h5py.
