### ISSUE TITLE
train.py AssertionError

### ISSUE THREAD

**Issue by acabadw22** [peteryuX/arcface-tf2#7]
Hello, It's so useful code.
but when I use ArcHead on training, It occur error like this.

Traceback (most recent call last):
  File "train.py", line 83, in <module>
    train()
  File "train.py", line 55, in train
    logist = model(inputs, training=True)
  File "/home/dukim/env/tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/dukim/env/tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/dukim/env/tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 870, in _run_internal_graph
    assert str(id(x)) in tensor_dict, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("ArcHead/Identity:0", shape=(None, 1200), dtype=float32)

**Comment by acabadw22** [comment]
I solved.

train.py
logist = model(inputs, training=True)
->
logist = model((inputs, labels), training=True)

**Comment by peteryuX** [comment]
Good! Thanks you!
